extends:
  - reearth
root: true
rules:
  import/order:
    - warn
    - pathGroups:
      - pattern: '@reearth/**'
        group: external
        position: after
      pathGroupsExcludedImportTypes: ["builtin"]
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
overrides:
  - files:
      - src/gql/queries/*.ts
      - src/gql/fragments/*.ts
    plugins:
      - graphql
    rules:
      graphql/capitalized-type-name:
        - error
        - env: apollo
      graphql/no-deprecated-fields:
        - error
        - env: apollo
      graphql/required-fields:
        - error
        - env: apollo
          requiredFields:
            - id
  - files:
      - src/**/*.graphql
    plugins:
      - graphql
    rules:
      graphql/template-strings:
        - error
        - env: literal
      graphql/capitalized-type-name:
        - error
        - env: literal
      graphql/no-deprecated-fields:
        - error
        - env: literal
      graphql/required-fields:
        - error
        - env: literal
          requiredFields:
            - id
  - files:
      - cypress/**/*
    extends:
      - reearth/node
      - plugin:cypress/recommended
