name: deploy_test
on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches: [main]
env:
  REEARTH_URL: test.reearth.dev
  GCS_DEST: gs://test.reearth.dev/
jobs:
  deploy_test:
    name: Deploy test env
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.repository.full_name == 'reearth/reearth-web'
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/nightly
          file: reearth-web_nightly.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: tar -xvf reearth-web_nightly.tar.gz
      - name: put reearth_config.json
        run: curl -L -o reearth-web/reearth_config.json https://${{ env.REEARTH_URL }}/reearth_config.json
      - name: rsync
        run: gsutil -m -h "Cache-Control:no-store" rsync -dr reearth-web/ ${{ env.GCS_DEST }}
  slack-notification:
    if: always()
    name: Slack Notification
    needs:
      - deploy_test
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: Gamesight/slack-workflow-status@master
        if: always()
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
