name: E2E test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  e2e_pre:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.e2e_pre.outputs.result }}
    env:
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
    steps:
      - name: Set vars
        id: e2e_pre
        run: echo "::set-output name=result::`test -n "$CYPRESS_PROJECT_ID" && echo 1`"
  e2e:
    name: E2E test
    runs-on: ubuntu-latest
    needs: e2e_pre
    if: needs.e2e_pre.outputs.result != null
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: E2E test
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_BASE_URL: https://test.reearth.dev
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_REEARTH_WEB_API: https://api.test.reearth.dev/api
          CYPRESS_REEARTH_WEB_AUTH0_AUDIENCE: ${{ secrets.REEARTH_WEB_AUTH0_AUDIENCE }}
          CYPRESS_REEARTH_WEB_AUTH0_CLIENT_ID: ${{ secrets.REEARTH_WEB_AUTH0_CLIENT_ID }}
          CYPRESS_REEARTH_WEB_AUTH0_DOMAIN: ${{ secrets.REEARTH_WEB_AUTH0_DOMAIN }}
          CYPRESS_REEARTH_WEB_E2E_USER_ID: ${{ secrets.REEARTH_WEB_E2E_USER_ID }}
          CYPRESS_REEARTH_WEB_E2E_TEAM_ID: ${{ secrets.REEARTH_WEB_E2E_TEAM_ID }}
          CYPRESS_REEARTH_WEB_E2E_USERNAME: ${{ secrets.REEARTH_WEB_E2E_USERNAME }}
          CYPRESS_REEARTH_WEB_E2E_PASSWORD: ${{ secrets.REEARTH_WEB_E2E_PASSWORD }}
          CYPRESS_REEARTH_WEB_E2E_USER_NAME: ${{ secrets.REEARTH_WEB_E2E_USER_NAME }}
          CYPRESS_REEARTH_WEB_E2E_SIGNUP_SECRET: ${{ secrets.REEARTH_WEB_E2E_SIGNUP_SECRET }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2etest-result
          if-no-files-found: ignore
          path: |
            cypress/screenshots
            cypress/videos
  slack-notification:
    if: success() || failure()
    name: Slack Notification
    needs:
      - e2e
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: Gamesight/slack-workflow-status@master
        if: always()
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
