name: Release
on:
  workflow_dispatch:
    inputs:
      custom_tag:
        required: false
        description: Specify version only when you want to increment the minor and major version (e.g. 1.1.0)
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GPT }}
      - name: Bump tag version
        id: tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.custom_tag }}
          dry_run: true
      - name: Update version of package.json
        env:
          TAG: ${{ steps.tag.outputs.new_tag }}
        run: |
          yarn version --no-git-tag-version --new-version ${TAG/v}
      - name: Prepare git-cliff
        id: cliff_pre
        run: |
          touch CHANGELOG.md CHANGELOG_latest.md
          PREV_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1) 2> /dev/null)
          if [[ $PREV_TAG == v*.*.* ]]; then
            echo "::set-output name=latest::--latest"
          fi
      - name: Generate changelog
        uses: orhun/git-cliff-action@v1
        env:
          OUTPUT: CHANGELOG.md
        with:
          config: .github/cliff.toml
          args: --verbose --tag ${{ steps.tag.outputs.new_tag }}
      - name: Generate latest changelog
        uses: orhun/git-cliff-action@v1
        id: changelog
        env:
          OUTPUT: CHANGELOG_latest.md
        with:
          config: .github/cliff.toml
          args: --verbose --strip all --tag ${{ steps.tag.outputs.new_tag }} ${{ steps.cliff_pre.outputs.latest }}
      - name: Format changelogs
        env:
          URL: ${{ github.event.repository.html_url }}
        run: |
          URL=${URL//\//\\\/}
          sed -i -E 's/<!-- [0-9]+ -->//g; s/\(#([0-9]+)\)/([#\1]('"$URL"'\/pull\/\1))/g; s/`([a-zA-Z0-9]+)`/[`\1`]('"$URL"'\/commit\/\1)/g' CHANGELOG*.md
          sed -i '/^## .*$/d; 1d; 2d' CHANGELOG_latest.md
      - name: Upload latest changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog-${{ steps.tag.outputs.new_tag }}
          path: CHANGELOG_latest.md
      - name: Commit & push
        env:
          TAG: ${{ steps.tag.outputs.new_tag }}
        run: |
          rm CHANGELOG_latest.md
          git add CHANGELOG.md
          git commit -am "$TAG"
          git tag $TAG
          git push
          git push --tags
