on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: changelog
        uses: reearth/changelog-action@main
      - name: Print version
        run: echo "$PREV_VERSION -> $VERSION"
        env:
          VERSION: ${{ steps.changelog.outputs.version }}
          PREV_VERSION: ${{ steps.changelog.outputs.prevVersion }}
      - name: Print CHANGELOG
        run: echo $CHANGELOG
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
      - name: Print CHANGELOG file
        run: cat CHANGELOG.md
